GSATPLAY_TUTORIAL_TEXTS = {
    first_page: {
        bold_text: 'PERDEU NA TV? ENCONTRE OS EPISÓDIOS MAIS RECENTES DE PROGRAMAS, ALÉM DE FILMES, NOVELAS, SÉRIES E SHOWS PARA ASSITIR LOGO APÓS A EXIBIÇÃO DA TV.',
        sub_text: 'ASSISTA ONDE E QUANDO QUISER, SEM PAGAR A MAIS POR ISSO',
        next_button: 'PRÓXIMO'
    },
    second_page: {
        bold_text: 'SABIA QUE VOCÊ PODE ASSISTIR AOS MELHORES CANAIS DA TV POR ASSINATURA EM UM MESMO APLICATIVO?',
        sub_text: 'SEUS PROGRAMAS FAVORITOS EM UM SÓ LUGAR',
        next_button: 'PRÓXIMO'
    },
    third_page: {
        bold_text: 'USE A BOLINHA E ACOMPANHE A PROGRAMAÇÃO DA TV EM TEMPO REAL',
        sub_text: 'TODOS OS CANAIS GLOBOSAT, MUDE DE CANAL QUANDO QUISER',
        next_button: 'PRÓXIMO'
    },
    fourth_page: {
        bold_text: 'ASSINANTES DAS OPERADORAS ABAIXO NÃO PAGAM NADA A MAIS PARA ASSISTIR ONLINE.',
        sub_text: 'ACESSE O SITE DA SUA OPERADORA DE TV, CRIE SEU LOGIN E APROVEITE.',
        next_button: 'OK, ENTENDI!'
    }
}
