# config/cucumber.yml
##YAML Template
---
android-vsp: PLATFORM=android -r features/support -r features/android -r features/step_definitions -r features/android/pages


ios-vsp: PLATFORM=ios APP_BUNDLE_PATH=prebuilt/GlobosatPlay.app  -r features/support -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages